[build]
  base = "/"
  publish = "dist/calendar/browser"
  command = "sed -i 's/SENTRY_RELEASE/'$COMMIT_REF'/g' src/environments/environment.prod.ts && npm run prerender"

[context.deploy-preview]
  command = "sed -i 's/SENTRY_RELEASE/'$COMMIT_REF'/g' src/environments/environment.preview.ts && npm run prerender -- --configuration=preview"

[context.deploy-preview.environment]
  SENTRY_ENVIRONMENT = "preview"

[[redirects]]
  from = "https://ecalendrier.pvsc.fr/*"
  to = "https://www.ecalendrier.net/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/calendars"
  to = "/calendars"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/privacy"
  status = 200

[[redirects]]
  from = "/edit/*"
  to = "/calendars"
  status = 200

[[redirects]]
  from = "/*"
  to = "/preview"
  status = 200
